name: 🐛 Bug
title: "Bug: "
description: Riporta Errori e Bug
labels: "type | bug"
body:
  - type: markdown
    attributes:
      value: |
        Grazie per aver aperto una segnalzione! 🎉
        Per favore, assicurati di aver letto il [File Leggimi](README.md)
        e di aver seguito le [Linee Guida](CONTRIBUTING.md) prima di aprire una segnalazione.
  - type: checkboxes
    attributes:
      label: "📝 Assicurati di aver controllato"
      description: Confermo di aver cercato fra le segnalazioni aperte e chiuse, ma non ho trovato nulla simile.
      required: true
  
  - type: textarea
    attributes:
      label: Sommario
      description: scivi un riassunto di cosa è successo.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Passi per riprodurre
      description: Passi per riprodurre l'errore / comportamento anomalo
      placeholder: |
        1. Fai questo '...'
        2. Poi fai questo '...'
        3. Ecco il Bug / Errore '...'
    validations:
      required: false
  
  - type: textarea
    attributes:
      laberl: Dalamud.Log
      description: Lo trovi qui `%AppData%\Roaming\XIVLauncher\Dalamud.log`, incollalo qui.
      render: text
    validations:
      required: false
  
  - type: dropdown
    attributes:
      label: Sistema Operativo
      description: Su quale sistema hai avuto il problema?
      options:
        - Windows
        - macOS
        - Linux
        - Altro (Specifica)
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Informazioni aggiuntive
      description: Qualsiasi altra informazione che ritieni utile.
    validations:
      required: false