name: 🐛 Bug
description: Segnala errori o comportamenti anomali
title: Bug
labels: "bug,needs-triage"
body:
- type: markdown
  id: thankyou
  attributes:
    value: |
      Grazie per questa segnalazione!
- type: dropdown
  id: check-confirm
  attributes:
    label: Confermi che hai cercato fra le issue esistenti e non hai trovato quello che cercavi?
    options:
      - Confermo
      - Le issue presenti non rispondono alla mia domanda
   validations:
    required: true
   
   
