name: 🐛 Report Bug
title: "Bug: "
description: Riporta comportamenti anomali o errori
labels: "type | bug"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a bug report! Please fill out the fields below to make it easier to work on your problem.

  - type: checkboxes
    attributes:
      label: Checklist Pre-report
      description: Prima di fare questo reporto, ho fatto quanto segue
      options:
        - label: Ho cercato fra le issue esistenti e non ho trovato la mia, o quelle esistente non risolvevano la mia domanda.
          required: true

  - type: textarea
    attributes:
      label: Sommario
      description: Scrivi sommariamente cosa succede
    validations:
      required: true

  - type: textarea
    attributes:
      label: Step per Riprodurre
      description: Steps per riprodurre il bug / errore
      placeholder: |
        1. Fai questo '...'
        2. Poi questo '...'
        3. Bug/Errore '...'
    validations:
      required: false

  - type: textarea
    attributes:
      label: Dalamud.log
      description: Lo trovi qui `%AppData%\Roaming\XIVLauncher\Dalamud.log`, incollalo qui.
      render: Text
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Sistema Operativo
      description: Su quale sistema si verifica?
      options:
        - Windows
        - Linux
        - MacOS
        - Non in lista (Scrivilo)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Info Addizionali
      description: Qualsiasi cosa ti venga in mente e che il team debba sapere.
    validations:
      required: false
